name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    name: Build and Package APKs
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Extract Commit Comments
        id: commit_comments
        run: |
          COMMENTS=""
          for COMMIT_HASH in $(git log --format="%h" ${{ github.event.before }}..${{ github.sha }}); do
            COMMIT_MESSAGE=$(git log --format="%s" -n 1 $COMMIT_HASH)
            COMMENTS="$COMMENTS$COMMIT_MESSAGE\n"
          done
          echo "::set-output name=COMMENT_MESSAGE::$COMMENTS"

      - name: Print Commit Comments
        run: echo "$COMMIT_MESSAGE"
          
