name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    name: Build and Package APKs
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
  
      - name: Extract and Comment on Push Commits
        run: |
          # 获取本次push的commit信息
          COMMITS=$(git log --pretty=format:"%h %s")
          
          # 将commit信息按行分割，并标注序号
          IFS=$'\n' read -r -a COMMIT_MESSAGES <<< "$COMMITS"
          COMMENT_MESSAGE=""
          for ((i=0; i<${#COMMIT_MESSAGES[@]}; i++)); do
            COMMENT_MESSAGE="$COMMENT_MESSAGE$((i+1)). ${COMMIT_MESSAGES[i]}\n"
          done
          
          # 输出COMMENT_MESSAGE变量
          echo $COMMENT_MESSAGE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
