name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    name: Build and Package APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Parse and number commit messages
        run: |
          COMMIT_MESSAGES=$(git log --oneline HEAD...HEAD^)
          COMMENT_MESSAGE=""
          IFS=$'\n'
          for MESSAGE in $COMMIT_MESSAGES; do
            COMMENT_MESSAGE="${COMMENT_MESSAGE}$(echo "$MESSAGE" | cut -d' ' -f2- | sed 's/^/[comment] /')\n"
          done
          echo "COMMENT_MESSAGE=${COMMENT_MESSAGE}" >> $GITHUB_ENV
          
