name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    name: Build and Package APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload APK to Backend
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api2.ifafu.cn/api/app/update/ci?token=${{ secrets.CI_TOKEN }}'
          method: 'POST'
          contentType: 'multipart/form-data'
          file: app-arm64-v8a-release.apk
