name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    name: Build and Package APKs
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Extract Commit Comments
        id: commit_comments
        run: |         
          COMMIT_MSG=$(echo '${{ toJson(github.event.commits) }}' | jq -r '.[] | .id[0:6] + " " + .message' | tr '\n' ' ')
          echo "COMMIT_MESSAGE=$COMMIT_MSG"
          
