name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    name: Build and Package APKs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        apk:
          - { name: 'app-arm64-v8a-release', path: 'build/app/outputs/apk/release/app-arm64-v8a-release.apk' }
          - { name: 'app-armeabi-v7a-release', path: 'build/app/outputs/apk/release/app-armeabi-v7a-release.apk' }
          - { name: 'app-x86_64-release', path: 'build/app/outputs/apk/release/app-x86_64-release.apk' }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Upload APK to Backend
        run: |
          UPLOAD_URL='https://api2.ifafu.cn/api/app/update/ci?token=${{ secrets.CI_TOKEN }}'
          FILE_PATH=app-arm64-v8a-release.apk
          COMMIT_MESSAGE=$(echo '${{ toJson(github.event.commits) }}' | jq -r '.[] | .id[0:6] + " " + .message')
          MESSAGE='$COMMIT_MESSAGE\n-- CI from ${{ github.ref }} - ${GITHUB_SHA::7}'
          curl -X POST -F "file=@$FILE_PATH" -F "message=$MESSAGE" $UPLOAD_URL