name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    name: Build and Package APKs
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Extract Commit Comments
        id: commit_comments
        run: |         
          echo "List of Commits in this Push:"
          for commit in ${{ github.event.commits }}; do
            for c in $commit; do
              echo "Commit: $c"
            done
          done
          
          
