name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    name: Build and Package APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract commit messages
        id: extract
        run: |
          messages=$(git log --format="%s" ${{ github.event.before }}..${{ github.sha }})
          message_list=""
          IFS=$'\n'  # Set Internal Field Separator to newline
          messages=($messages)
          for ((i=0; i<${#messages[@]}; i++)); do
            message_list="${message_list}${i}. ${messages[i]}\n"
          done
          echo "::set-output name=commit_messages::${message_list}"
        shell: bash

      - name: Display commit messages
        run: echo "${{ steps.extract.outputs.commit_messages }}"
          
